export const questions = [
    {
       id:1,
       question:'Hangisi 2nin katıdır?',
       answers:[
        {option:'A)',answer:'9'},
        {option:'B)',answer:'5'},
        {option:'C)',answer:'3'},
        {option:'D)',answer:'4'},
       ],
       correctAnswer:'4',
       category:'Maths',
       difficulty:'Easy',
       type:'Multiple'
    },
    {
        id:2,
        question:'3 + 5 kaçtır?',
        answers:[
         {option:'A)',answer:'5'},
         {option:'B)',answer:'6'},
         {option:'C)',answer:'7'},
         {option:'D)',answer:'8'},
          ],
        correctAnswer:'8',
        category:'Maths',
        difficulty:'Easy',
        type:'Multiple'
     },
     {
        id:3,
        question:'5 + 9 kaçtır?',
        answers:[
         {option:'A)',answer:'12'},
         {option:'B)',answer:'14'},
         {option:'C)',answer:'10'},
         {option:'D)',answer:'19'},
          ],
        correctAnswer:'14',
        category:'Maths',
        difficulty:'Easy',
        type:'Multiple'
     },
     {
        id:4,
        question:'Hangisi 2nin katıdırrrrrrrrrrrrrrrrrrrr?',
        answers:[
         {option:'A)',answer:'9'},
         {option:'B)',answer:'5'},
         {option:'C)',answer:'3'},
         {option:'D)',answer:'4'},
          ],
        correctAnswer:'4',
        category:'Maths',
        difficulty:'Easy',
        type:'Multiple'
     },
     {
         id:5,
         question:'Hangisi 2nin katıdır?',
         answers:[
            {option:'A)',answer:'9'},
            {option:'B)',answer:'5'},
            {option:'C)',answer:'3'},
            {option:'D)',answer:'4'},
          ],
         correctAnswer:'4',
         category:'Maths',
         difficulty:'Easy',
         type:'Multiple'
      },
      {
         id:6,
         question:'Hangisi 2nin katıdır?',
         answers:[
            {option:'A)',answer:'9'},
            {option:'B)',answer:'5'},
            {option:'C)',answer:'3'},
            {option:'D)',answer:'4'},
          ],
         correctAnswer:'4',
         category:'Maths',
         difficulty:'Medium',
         type:'Multiple'
      },
      {
        id:7,
        question:'Hangisi 2nin katıdır?',
        answers:[
         {option:'A)',answer:'9'},
         {option:'B)',answer:'5'},
         {option:'C)',answer:'3'},
         {option:'D)',answer:'4'},
          ],
        correctAnswer:'4',
        category:'Maths',
        difficulty:'Medium',
        type:'Multiple'
     },
     {
         id:8,
         question:'Hangisi 2nin katıdır?',
         answers:[
            {option:'A)',answer:'9'},
            {option:'B)',answer:'5'},
            {option:'C)',answer:'3'},
            {option:'D)',answer:'4'},
          ],
         correctAnswer:'4',
         category:'Maths',
         difficulty:'Medium',
         type:'Multiple'
      },
      {
         id:9,
         question:'Hangisi 2nin katıdır?',
         answers:[
            {option:'A)',answer:'9'},
            {option:'B)',answer:'5'},
            {option:'C)',answer:'3'},
            {option:'D)',answer:'4'},
          ],
         correctAnswer:'4',
         category:'Maths',
         difficulty:'Medium',
         type:'Multiple'
      },
      {
        id:10,
        question:'Hangisi 2nin katıdır?',
        answers:[
         {option:'A)',answer:'9'},
         {option:'B)',answer:'5'},
         {option:'C)',answer:'3'},
         {option:'D)',answer:'4'},
          ],
        correctAnswer:'4',
        category:'Maths',
        difficulty:'Medium',
        type:'Multiple'
     },
     {
         id:11,
         question:'Hangisi 2nin katıdır?',
         answers:[
            {option:'A)',answer:'9'},
            {option:'B)',answer:'5'},
            {option:'C)',answer:'3'},
            {option:'D)',answer:'4'},
          ],
         correctAnswer:'4',
         category:'Maths',
         difficulty:'Hard',
         type:'Multiple'
      },
      {
         id:12,
         question:'Hangisi 2nin katıdır?',
         answers:[
            {option:'A)',answer:'9'},
            {option:'B)',answer:'5'},
            {option:'C)',answer:'3'},
            {option:'D)',answer:'4'},
          ],
         correctAnswer:'4',
         category:'Maths',
         difficulty:'Hard',
         type:'Multiple'
      },
      {
        id:13,
        question:'Hangisi 2nin katıdır?',
        answers:[
         {option:'A)',answer:'9'},
         {option:'B)',answer:'5'},
         {option:'C)',answer:'3'},
         {option:'D)',answer:'4'},
          ],
        correctAnswer:'4',
        category:'Maths',
        difficulty:'Hard',
        type:'Multiple'
     },
     {
        id:14,
        question:'Hangisi 2nin katıdır?',
        answers:[
         {option:'A)',answer:'9'},
         {option:'B)',answer:'5'},
         {option:'C)',answer:'3'},
         {option:'D)',answer:'4'},
          ],
        correctAnswer:'4',
        category:'Maths',
        difficulty:'Hard',
        type:'Multiple'
     },
     {
        id:15,
        question:'Hangisi 2nin katıdır?',
        answers:[
         {option:'A)',answer:'9'},
         {option:'B)',answer:'5'},
         {option:'C)',answer:'3'},
         {option:'D)',answer:'4'},
          ],
        correctAnswer:'4',
        category:'Maths',
        difficulty:'Hard',
        type:'Multiple'
     },
     {
        id:16,
        question:'İkinin küpü 8 dir',
        answers:[
           {answer:'Doğru'},
           {answer:'Yanlış'}
        ],
        correctAnswer:'Doğru',
        category:'Maths',
        difficulty:'Easy',
        type:'TrueFalse'
     }
     ,
     {
        id:17,
        question:'İkinin küpü 8 dir',
        answers:[
           {answer:'Doğru'},
           {answer:'Yanlış'}
        ],
        correctAnswer:'Doğru',
        category:'Maths',
        difficulty:'Easy',
        type:'TrueFalse'
     }
     ,
     {
        id:18,
        question:'İkinin küpü 8 dir',
        answers:[
           {answer:'Doğru'},
           {answer:'Yanlış'}
        ],
        correctAnswer:'Doğru',
        category:'Maths',
        difficulty:'Easy',
        type:'TrueFalse'
     }
     ,
     {
        id:19,
        question:'İkinin küpü 8 dir',
        answers:[
           {answer:'Doğru'},
           {answer:'Yanlış'}
        ],
        correctAnswer:'Doğru',
        category:'Maths',
        difficulty:'Easy',
        type:'TrueFalse'
     }
     ,
     {
        id:20,
        question:'İkinin küpü 8 dir',
        answers:[
           {answer:'Doğru'},
           {answer:'Yanlış'}
        ],
        correctAnswer:'Doğru',
        category:'Maths',
        difficulty:'Easy',
        type:'TrueFalse'
     }
     ,
     {
        id:21,
        question:'İkinin küpü 8 dir',
        answers:[
           {answer:'Doğru'},
           {answer:'Yanlış'}
        ],
        correctAnswer:'Doğru',
        category:'Maths',
        difficulty:'Medium',
        type:'TrueFalse'
     }
     ,
     {
        id:22,
        question:'İkinin küpü 8 dir',
        answers:[
           {answer:'Doğru'},
           {answer:'Yanlış'}
        ],
        correctAnswer:'Doğru',
        category:'Maths',
        difficulty:'Medium',
        type:'TrueFalse'
     }
     ,
     {
        id:23,
        question:'İkinin küpü 8 dir',
        answers:[
           {answer:'Doğru'},
           {answer:'Yanlış'}
        ],
        correctAnswer:'Doğru',
        category:'Maths',
        difficulty:'Medium',
        type:'TrueFalse'
     }
     ,
     {
        id:24,
        question:'İkinin küpü 8 dir',
        answers:[
           {answer:'Doğru'},
           {answer:'Yanlış'}
        ],
        correctAnswer:'Doğru',
        category:'Maths',
        difficulty:'Medium',
        type:'TrueFalse'
     }
     ,
     {
        id:25,
        question:'İkinin küpü 8 dir',
        answers:[
           {answer:'Doğru'},
           {answer:'Yanlış'}
        ],
        correctAnswer:'Doğru',
        category:'Maths',
        difficulty:'Medium',
        type:'TrueFalse'
     }
     ,
     {
        id:26,
        question:'İkinin küpü 8 dir',
        answers:[
           {answer:'Doğru'},
           {answer:'Yanlış'}
        ],
        correctAnswer:'Doğru',
        category:'Maths',
        difficulty:'Hard',
        type:'TrueFalse'
     }
     ,
     {
        id:27,
        question:'İkinin küpü 8 dir',
        answers:[
           {answer:'Doğru'},
           {answer:'Yanlış'}
        ],
        correctAnswer:'Doğru',
        category:'Maths',
        difficulty:'Hard',
        type:'TrueFalse'
     }
     ,
     {
        id:28,
        question:'İkinin küpü 8 dir',
        answers:[
           {answer:'Doğru'},
           {answer:'Yanlış'}
        ],
        correctAnswer:'Doğru',
        category:'Maths',
        difficulty:'Hard',
        type:'TrueFalse'
     }
     ,
     {
        id:29,
        question:'İkinin küpü 8 dir',
        answers:[
           {answer:'Doğru'},
           {answer:'Yanlış'}
        ],
        correctAnswer:'Doğru',
        category:'Maths',
        difficulty:'Hard',
        type:'TrueFalse'
     }
     ,
     {
        id:30,
        question:'İkinin küpü 8 dir',
        answers:[
           {answer:'Doğru'},
           {answer:'Yanlış'}
        ],
        correctAnswer:'Doğru',
        category:'Maths',
        difficulty:'Hard',
        type:'TrueFalse'
     }
     ,
     {
        id:31,
        question:'Üçün karesi ... dir',
        answers:[
           {answer:'12'},
           {answer:'6'},
           {answer:'9'},
           {answer:'15'},
          ],
        correctAnswer:'9',
        category:'Maths',
        difficulty:'Easy',
        type:'Space'
     }
     ,
     {
        id:32,
        question:'Üçün karesi ... dir',
        answers:[
           {answer:'12'},
           {answer:'6'},
           {answer:'9'},
           {answer:'15'},
          ],
        correctAnswer:'9',
        category:'Maths',
        difficulty:'Easy',
        type:'Space'
     }
     ,
     {
        id:33,
        question:'Üçün karesi ... dir',
        answers:[
           {answer:'12'},
           {answer:'6'},
           {answer:'9'},
           {answer:'15'},
          ],
        correctAnswer:'9',
        category:'Maths',
        difficulty:'Easy',
        type:'Space'
     }
     ,
     {
        id:34,
        question:'Üçün karesi ... dir',
        answers:[
           {answer:'12'},
           {answer:'6'},
           {answer:'9'},
           {answer:'15'},
          ],
        correctAnswer:'9',
        category:'Maths',
        difficulty:'Easy',
        type:'Space'
     }
     ,
     {
        id:35,
        question:'Üçün karesi ... dir',
        answers:[
           {answer:'12'},
           {answer:'6'},
           {answer:'9'},
           {answer:'15'},
          ],
        correctAnswer:'9',
        category:'Maths',
        difficulty:'Easy',
        type:'Space'
     }
     ,
     {
        id:36,
        question:'Üçün karesi ... dir',
        answers:[
           {answer:'12'},
           {answer:'6'},
           {answer:'9'},
           {answer:'15'},
          ],
        correctAnswer:'9',
        category:'Maths',
        difficulty:'Medium',
        type:'Space'
     }
     ,
     {
        id:37,
        question:'Üçün karesi ... dir',
        answers:[
           {answer:'12'},
           {answer:'6'},
           {answer:'9'},
           {answer:'15'},
          ],
        correctAnswer:'9',
        category:'Maths',
        difficulty:'Medium',
        type:'Space'
     }
     ,
     {
        id:38,
        question:'Üçün karesi ... dir',
        answers:[
           {answer:'12'},
           {answer:'6'},
           {answer:'9'},
           {answer:'15'},
          ],
        correctAnswer:'9',
        category:'Maths',
        difficulty:'Medium',
        type:'Space'
     }
     ,
     {
        id:39,
        question:'Üçün karesi ... dir',
        answers:[
           {answer:'12'},
           {answer:'6'},
           {answer:'9'},
           {answer:'15'},
          ],
        correctAnswer:'9',
        category:'Maths',
        difficulty:'Medium',
        type:'Space'
     }
     ,
     {
        id:40,
        question:'Üçün karesi ... dir',
        answers:[
           {answer:'12'},
           {answer:'6'},
           {answer:'9'},
           {answer:'15'},
          ],
        correctAnswer:'9',
        category:'Maths',
        difficulty:'Medium',
        type:'Space'
     }
     ,
     {
        id:41,
        question:'Üçün karesi ... dir',
        answers:[
           {answer:'12'},
           {answer:'6'},
           {answer:'9'},
           {answer:'15'},
          ],
        correctAnswer:'9',
        category:'Maths',
        difficulty:'Hard',
        type:'Space'
     }
     ,
     {
        id:42,
        question:'Üçün karesi ... dir',
        answers:[
           {answer:'12'},
           {answer:'6'},
           {answer:'9'},
           {answer:'15'},
          ],
        correctAnswer:'9',
        category:'Maths',
        difficulty:'Hard',
        type:'Space'
     }
     ,
     {
        id:43,
        question:'Üçün karesi ... dir',
        answers:[
           {answer:'12'},
           {answer:'6'},
           {answer:'9'},
           {answer:'15'},
          ],
        correctAnswer:'9',
        category:'Maths',
        difficulty:'Hard',
        type:'Space'
     }
     ,
     {
        id:44,
        question:'Üçün karesi ... dir',
        answers:[
           {answer:'12'},
           {answer:'6'},
           {answer:'9'},
           {answer:'15'},
          ],
        correctAnswer:'9',
        category:'Maths',
        difficulty:'Hard',
        type:'Space'
     }
     ,
     {
        id:45,
        question:'Üçün karesi ... dir',
        answers:[
           {answer:'12'},
           {answer:'6'},
           {answer:'9'},
           {answer:'15'},
          ],
        correctAnswer:'9',
        category:'Maths',
        difficulty:'Hard',
        type:'Space'
     }
     

]